services:
  - type: web
    name: infosys-inventory-api-blueprint
    runtime: docker
    repo: https://github.com/saran-200612/infosysproject
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /invent/health
    autoDeploy: true
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://infosysprojectfrontend.vercel.app
      - key: SESSION_COOKIE_SAMESITE
        value: None
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: DDL_AUTO
        value: update
      - key: SHOW_SQL
        value: "false"
